server:
  port: 8002

  servlet:
    context-path: /shoolmanage_consumer

dubbo:
  application:
    name: consumer

  registry:
    address: zookeeper://192.168.88.129:2181


spring:
  #数据源配置
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolmanage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456