server:
  port: 8001

  servlet:
    context-path: /shoolmanage_provider

dubbo:
  application:
    name: provider

  registry:
    address: zookeeper://192.168.88.129:2181
    timeout: 6000

  protocol:
    name: dubbo
    port: 20880

  scan:
    base-packages: com.lixun.provider.service

spring:
  #数据源配置
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolmanage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456


# mybatis配置
mybatis:
  # 映射文件路径
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.lixun.api.pojo
  configuration:
    # 下划线转驼峰配置
    map-underscore-to-camel-case: true


# 显示dao 执行sql语句
logging:
  level:
    com:
      lixun:
        provider:
          dao: debug
